# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=16)),
                ('status', models.IntegerField()),
                ('rf_band', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('registered_time', models.DateField(auto_now_add=True)),
                ('longitude', models.FloatField(max_length=8)),
                ('latitude', models.FloatField(max_length=8)),
                ('memo', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
