# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hub', '0002_auto_20170901_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hub',
            name='deleted_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='registered_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hub',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
