# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hub', '0004_auto_20170901_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='memo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
