# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hub', '0005_auto_20170901_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='registered_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
