# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '用户')], default=2),
        ),
    ]
