# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
