# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_hub', '0006_auto_20170901_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=16)),
                ('sequence', models.CharField(max_length=8)),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '故障')], default=0)),
                ('type', models.SmallIntegerField(choices=[(1, '钠灯'), (2, 'LED')], default=1)),
                ('is_repeater', models.BooleanField(default='False')),
                ('rf_band', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('registered_time', models.DateField(auto_now_add=True)),
                ('longitude', models.FloatField(max_length=8)),
                ('latitude', models.FloatField(max_length=8)),
                ('memo', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(db_index=True, null=True)),
                ('hub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamp_set', to='manage_hub.Hub', verbose_name='所属集控')),
            ],
        ),
    ]
