# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_lamp', '0005_auto_20170903_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='hub_sn',
            field=models.CharField(max_length=16),
        ),
    ]
