# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_lamp', '0006_auto_20170903_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='registered_time',
            field=models.DateField(),
        ),
    ]
