# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='to_accounts',
            field=models.ManyToManyField(related_name='group_profile_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
