# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(default=b'PUB', max_length=255, null=True)),
                ('uuid', models.CharField(default=b'No Uuid', max_length=255, null=True, unique=True)),
                ('size', models.BigIntegerField(null=True)),
                ('is_file', models.BooleanField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
    ]
